#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
bindkey -v

#following is necessary for playing with some ruby application, its a pain getting the ruby gem path right 
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

alias vim="nvim"
alias x2frank="ssh -Y frankenpad x2x -to :0 -west" 
alias eclipse="/home/mracine/java-latest-released/eclipse/eclipse"
alias glogr="git log --graph --decorate --oneline --abbrev-commit"

#Following lines all control the insert or  command prompt color in zsh
INSERT_PROMPT="gray"	# urxvt (and family) accepts even #RRGGBB
COMMAND_PROMPT="red"

# helper for setting color including all kinds of terminals
set_prompt_color() {
    if [[ $TERM = "linux" ]]; then
       # nothing
    elif [[ $TMUX != '' ]]; then
        printf '\033Ptmux;\033\033]12;%b\007\033\\' "$1"
    else
        echo -ne "\033]12;$1\007"
    fi
}

# change cursor color basing on vi mode
zle-keymap-select () {
    if [ $KEYMAP = vicmd ]; then
        set_prompt_color $COMMAND_PROMPT
    else
        set_prompt_color $INSERT_PROMPT
    fi
}

zle-line-finish() {
    set_prompt_color $INSERT_PROMPT
}

zle-line-init () {
    zle -K viins
    set_prompt_color $INSERT_PROMPT
}

zle -N zle-keymap-select
zle -N zle-line-init
zle -N zle-line-finish

